version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        PIPENV_CHECK: "${PIPENV_CHECK:-1}"
    command: bash -c "cd /engine && ./run_tests.sh"
