openapi: "3.0.0"

info:
  title: Vulnerability Engine Manager Admin
  version: {{ app_version }}

paths:
  /version:
    get:
      summary: Application version
      description: Get application version.
      operationId: manager.version_handler.GetVersion.get
      x-methodName: getVersion
      responses:
        200:
          description: Application version.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/VersionOut'

  /systems/missing_in_inventory:
    get:
      summary: Get count of systems in system_platform table but missing in inventory.
      description: Get count of systems in system_platform table but missing in inventory. Admin interface, available only to admin users.
      operationId: manager.admin_handler.GetMissingInInventory.get
      x-methodName: getMissingInInventory
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Count of systems missing in inventory.
    delete:
      summary: Delete systems from system_platform table missing in inventory.
      description: Delete systems from system_platform table missing in inventory. Admin interface, available only to admin users.
      operationId: manager.admin_handler.DeleteMissingInInventory.delete
      x-methodName: deleteMissingInInventory
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Systems deleted.
        503:
          description: Service is running in read-only mode.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
  
  /taskomatic/run/{job_name}:
    put:
      summary: Trigger immediate run of taskomatic job with given name.
      description: Trigger immediate run of taskomatic job with given name. Admin interface, available only to admin users.
      operationId: manager.admin_handler.TaskomaticRun.put
      x-methodName: taskomaticRun
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: job_name
          description: Job name.
          required: true
          schema:
            type: string
          example: stale_systems
      responses:
        200:
          description: Job run triggered.
        404:
          description: Job with given name not found.

  /vmaas/sync:
    put:
      summary: Trigger immediate run of sync in vmaas_sync.
      description: Trigger immediate run of sync in vmaas_sync. Admin interface, available only to admin users.
      operationId: manager.admin_handler.VmaasSync.put
      x-methodName: vmaasSync
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Run triggered.

  /vmaas/re-evaluate:
    put:
      summary: Trigger immediate run of re-evaluation in vmaas_sync.
      description: Trigger immediate run of re-evaluation in vmaas_sync. Admin interface, available only to admin users.
      operationId: manager.admin_handler.VmaasReEvaluate.put
      x-methodName: vmaasReEvaluate
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Run triggered.

  /cves/{cve_id}:
    delete:
      summary: Delete CVE with given name.
      description: Delete CVE with given name. Deletes this CVE from all associated systems. Admin interface, available only to admin users.
      operationId: manager.admin_handler.DeleteCve.delete
      x-methodName: deleteCve
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: cve_id
          description: CVE name.
          required: true
          schema:
            type: string
          example: CVE-2020-1111
      responses:
        200:
          description: CVE deleted.

  /content_version:
    get:
      summary: Get content revisions.
      description: Get revisions of content imported to Vulnerability application.
      operationId: manager.admin_handler.GetContentVersion.get
      x-methodName: getContentVersion
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Content revisions.
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  insights_content_vulnerability:
                    type: string
                    example: 5ec1896cefc6d3de960a80742fe513091e065cfd
                    description: SHA of latest commit imported for content repository.
                  insights_content_vulnerability_repo:
                    type: string
                    example: https://github.com/RedHatInsights/insights-content-vulnerability.git
                    description: URL of content repository.
                  insights_playbooks:
                    type: string
                    example: c702f6358a8e49590308ee005a175e7378852c7b
                    description: SHA of latest commit imported for playbooks repository.
                  insights_playbooks_repo:
                    type: string
                    example: https://github.com/RedHatInsights/insights-playbooks.git
                    description: URL of playbooks repository.

  /v1/statistics/{timestamp}:
    delete:
      summary: Delete records from stats table LESS THAN or EQUAL to timestamp.
      description: Deletes records from stats table which has dates less than or equal than given timestamp.
      operationId: manager.admin_handler.DeleteStatistics.delete
      x-methodName: DeleteStatistics
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: timestamp
          description: Timestamp in format %Y-%m-%d.
          required: true
          schema:
            type: string
          example: 2021-06-01
      responses:
        200:
          description: Records deleted
        400:
          description: Error message

  /database/queries:
    get:
      summary: Get list of running queries.
      description: Get statistics about active running queries, defined by threshold.
      operationId: manager.admin_handler.GetQueries.get
      x-methodName: getQueries
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: query
          name: ms_threshold
          schema:
            type: number
          description: Threshold in ms for the minimum running query.
        - in: query
          name: username
          schema:
            type: string
          description: Search for queries by author
        - in: query
          name: wait_event_type
          schema:
            type: string
          description: Filter queries by event wait event type
          example: Lock
      responses:
        200:
          description: Queries result.
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  queries:
                    type: array
                    items:
                      type: object
                      properties:
                        pid:
                          type: integer
                          example: 40277
                          description: PID of the DB server process
                        db_name:
                          type: string
                          example: vulnerability
                          description: Name of the database where process is connected
                        username:
                          type: string
                          example: ve_db_user_listener
                          description: Author of the query
                        app_name:
                          type: string
                          example: psql
                          description: Name of the application that is connected
                        query_start:
                          type: string
                          example: 2021-06-10 11:03:18.824233+00
                          description: Timestamp when query execution started
                        running_time:
                          type: string
                          example: 0:00:02.644451
                          description: Duration of query execution
                        wait_event_type:
                          type: string
                          example: LWLock
                          description: Signifies the type of waiting event
                        wait_event:
                          type: string
                          example: ControlFileLock
                          description: Wait event name in backend
                        query:
                          type: string
                          example: select system_profile->'operating_system' from inventory.host where system_profile->'operating_system' is not null;
                          description: Actual running query

  /database/query/{pid}:
    delete:
      summary: Kill a query execution by PID.
      description: Kill query by provided PID.
      operationId: manager.admin_handler.KillQuery.delete
      x-methodName: killQuery
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: pid
          schema:
            type: integer
          description: PID running the query
          required: true
      responses:
        200:
          description: Query killed

  /database/vacuum/table/{table_name}:
    get:
      summary: Start vacuum on table.
      description: Starts a pg_repack process to vacuum a table.
      operationId: manager.admin_handler.VacuumTable.get
      x-methodName: vacuumTable
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: table_name
          schema:
            type: string
          description: Name of the table NEEDS to be with schema name.
          example: public.system_platform
          required: True
        - in: query
          name: only_indexes
          schema:
            type: boolean
          description: If true, vacuums only indexes of table.
      responses:
        200:
          description: Vacuuming started.

  /database/vacuum/user/{rh_account_id}:
    get:
      summary: Vacuum system_vulnerabilities table occupied by user.
      description: Starts a pg_repack process to partitioned sv tables vacuum which has data by given user id.
      operationId: manager.admin_handler.VacuumUser.get
      x-methodName: vacuumUser
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: rh_account_id
          schema:
            type: integer
          description: ID of the user.
          required: True
      responses:
        200:
          description: Vacuuming started.

  /database/bloat/table/{table_name}:
    get:
      summary: Get bloat statistics for given database table.
      description: Gets the bloat statistics for the database table.
      operationId: manager.admin_handler.GetBloat.get
      x-methodName: getTableBloat
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: table_name
          schema:
            type: string
          description: Name of the table in schema.
          required: True
      responses:
        200:
          description: Bloat result.
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  table_len:
                    type: integer
                    description: Physical relation length in bytes
                    example: 8192
                  tuple_count:
                    type: integer
                    description: Number of live tuples
                    example: 19
                  tuple_len:
                    type: integer
                    description: Total length of live tuples in bytes
                    example: 3956
                  tuple_percent:
                    type: number
                    description: Percentage of live tuples
                    example: 48.29
                  dead_tuple_count:
                    type: integer
                    description: Number of dead tuples
                    example: 0
                  dead_tuple_len:
                    type: integer
                    description: Total length of dead tuples in bytes
                    example: 0
                  dead_tuple_percent:
                    type: number
                    description: Percentage of dead tuples
                    example: 0
                  free_space:
                    type: integer
                    description: Total free space in bytes
                    example: 4024
                  free_percent:
                    type: number
                    description: Percentage of free space
                    example: 49.12

  /database/bloat/user/{rh_account_id}:
    get:
      summary: Get table statistics for user.
      description: Get system_vulnerabilities table statistics for given user id.
      operationId: manager.admin_handler.GetUserBloat.get
      x-methodName: GetUserBloat
      security:
        - ApiKeyAuthAdmin: []
      parameters:
        - in: path
          name: rh_account_id
          schema:
            type: integer
          description: ID of the user.
          required: True
      responses:
        200:
          description: Bloat results.
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  tables:
                    type: array
                    items:
                      type: object
                      properties:
                        table_name:
                          type: string
                          description: Name of the table with user info.
                          example: system_vulnerabilities_active_101
                        table_len:
                          type: integer
                          description: Physical relation length in bytes
                          example: 8192
                        tuple_count:
                          type: integer
                          description: Number of live tuples
                          example: 19
                        tuple_len:
                          type: integer
                          description: Total length of live tuples in bytes
                          example: 3956
                        tuple_percent:
                          type: number
                          description: Percentage of live tuples
                          example: 48.29
                        dead_tuple_count:
                          type: integer
                          description: Number of dead tuples
                          example: 0
                        dead_tuple_len:
                          type: integer
                          description: Total length of dead tuples in bytes
                          example: 0
                        dead_tuple_percent:
                          type: number
                          description: Percentage of dead tuples
                          example: 0
                        free_space:
                          type: integer
                          description: Total free space in bytes
                          example: 4024
                        free_percent:
                          type: number
                          description: Percentage of free space
                          example: 49.12


components:
  parameters:
    inventory_id:
      in: path
      name: inventory_id
      description: Inventory ID.
      required: true
      schema:
        type: string
      example: INV-ID-0000-1234

    cve_id:
      in: path
      name: cve_id
      description: CVE id.
      required: true
      schema:
        type: string
      example: CVE-2016-0800

    account_id:
      in: path
      name: account_id
      description: Account ID of user.
      required: true
      schema:
        type: string
      example: '123456'

  securitySchemes:
    ApiKeyAuthAdmin:
      type: apiKey
      in: header
      name: x-rh-identity
      description: Identity header provided by Turnpike (for non-prod testing only).
      x-apikeyInfoFunc: manager.base.auth_admin

  schemas:
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              detail:
                type: string
                description: Error detail.
                example: Record not found.
              status:
                type: string
                description: String representation of HTTP status code.
                example: 404
            required:
              - detail
              - status
          minItems: 1
      required:
        - errors

    VersionOut:
      type: object
      properties:
        application_version:
          type: string
          description: Version of application.
          example: 0.1.2
        database_version:
          oneOf:
            - type: string
            - type: number
          description: Version of database schema.
          example: 1
      required:
        - application_version
        - database_version
