openapi: "3.0.0"

info:
  title: Vulnerability Engine Manager
  version: {{ app_version }}


paths:
  /healthz:
    get:
      summary: Health status of application
      description: Checks database availability and API response threshold time.
      operationId: manager.api_status_handler.GetApiStatus.get
      x-methodName: getApiStatus
      responses:
        200:
          description: API is healthy
        503:
          description: Database is unavaiable
  /metrics:
    get:
      summary: Application metrics
      description: Return prometheus metrics
      operationId: manager.main.metrics
      x-methodName: getMetrics
      responses:
        200:
          description: Application metrics
          content:
            text/plain:
              schema:
                type: string
