openapi: "3.0.0"

info:
  title: Vulnerability Engine Manager
  version: {{ app_version }}


paths:
  /healthz:
    get:
      summary: Health status of application
      description: Checks database availability and API response threshold time.
      operationId: manager.api_status_handler.GetApiStatus.get
      x-methodName: getApiStatus
      responses:
        200:
          description: API is healthy
        408:
          description: API is down (time out)
        503:
          description: Database is unavaiable
