openapi: "3.0.0"

info:
  title: Vulnerability Engine Manager Admin
  version: {{ app_version }}

paths:
  /version:
    get:
      summary: Application version
      description: Get application version.
      operationId: manager.version_handler.GetVersion.get
      x-methodName: getVersion
      responses:
        200:
          description: Application version.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/VersionOut'
  
  /refresh/accounts/{account_id}:
    put:
      summary: Refresh cached counts for given account ID.
      description: Refresh cached counts for given account ID. Admin interface, available only to internal users.
      operationId: manager.admin_handler.RefreshAccount.put
      x-methodName: refreshAccount
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Cached counts for given account successfully updated.
        404:
          description: Account was not found.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        503:
          description: Service is running in read-only mode.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
      parameters: 
        - $ref: '#/components/parameters/account_id'

  /refresh/accounts/{account_id}/cves/{cve_id}:
    put:
      summary: Refresh cached counts for given account ID and CVE.
      description: Refresh cached counts for given account ID and CVE. Admin interface, available only to admin users.
      operationId: manager.admin_handler.RefreshAccountCve.put
      x-methodName: refreshAccountCve
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Cached counts for given account and CVE successfully updated.
        404:
          description: Account or CVE was not found.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        503:
          description: Service is running in read-only mode.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
      parameters: 
        - $ref: '#/components/parameters/account_id'
        - $ref: '#/components/parameters/cve_id'

  /refresh/cves/{cve_id}:
    put:
      summary: Refresh cached counts for given CVE.
      description: Refresh cached counts for given CVE. Admin interface, available only to admin users.
      operationId: manager.admin_handler.RefreshCve.put
      x-methodName: refreshCve
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Cached counts for given CVE successfully updated.
        404:
          description: CVE was not found.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        503:
          description: Service is running in read-only mode.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
      parameters: 
        - $ref: '#/components/parameters/cve_id'

  /refresh/systems/{inventory_id}:
    put:
      summary: Refresh cached counts for given inventory ID.
      description: Refresh cached counts for given inventory ID. Admin interface, available only to admin users.
      operationId: manager.admin_handler.RefreshSystem.put
      x-methodName: refreshSystem
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Cached counts for given system successfully updated.
        404:
          description: System was not found.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
        503:
          description: Service is running in read-only mode.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
      parameters: 
        - $ref: '#/components/parameters/inventory_id'
  
  /systems/missing_in_inventory:
    get:
      summary: Get count of systems in system_platform table but missing in inventory.
      description: Get count of systems in system_platform table but missing in inventory. Admin interface, available only to admin users.
      operationId: manager.admin_handler.GetMissingInInventory.get
      x-methodName: getMissingInInventory
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Count of systems missing in inventory.
    delete:
      summary: Delete systems from system_platform table missing in inventory.
      description: Delete systems from system_platform table missing in inventory. Admin interface, available only to admin users.
      operationId: manager.admin_handler.DeleteMissingInInventory.delete
      x-methodName: deleteMissingInInventory
      security:
        - ApiKeyAuthAdmin: []
      responses:
        200:
          description: Systems deleted.
        503:
          description: Service is running in read-only mode.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'

components:
  parameters:
    inventory_id:
      in: path
      name: inventory_id
      description: Inventory ID.
      required: true
      schema:
        type: string
      example: INV-ID-0000-1234

    cve_id:
      in: path
      name: cve_id
      description: CVE id.
      required: true
      schema:
        type: string
      example: CVE-2016-0800

    account_id:
      in: path
      name: account_id
      description: Account ID of user.
      required: true
      schema:
        type: string
      example: '123456'

  securitySchemes:
    ApiKeyAuthAdmin:
      type: apiKey
      in: header
      name: x-rh-identity
      description: Identity header provided by Turnpike (for non-prod testing only).
      x-apikeyInfoFunc: manager.base.auth_admin

  schemas:
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              detail:
                type: string
                description: Error detail.
                example: Record not found.
              status:
                type: string
                description: String representation of HTTP status code.
                example: 404
            required:
              - detail
              - status
          minItems: 1
      required:
        - errors

    VersionOut:
      type: object
      properties:
        application_version:
          type: string
          description: Version of application.
          example: 0.1.2
        database_version:
          oneOf:
            - type: string
            - type: number
          description: Version of database schema.
          example: 1
      required:
        - application_version
        - database_version
