openapi: "3.0.0"

info:
  title: Vulnerability Engine PDF Exporter

paths:
  /v1/version:
    get:
      summary: Application version
      description: Get application version.
      operationId: pdf_exporter.version_handler.GetVersion.get
      x-methodName: getVersion
      responses:
        200:
          description: Application version.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/VersionOut'

  /v1/export:
    get:
      summary: Export to PDF
      description: Export HTML page to PDF.
      operationId: pdf_exporter.export_handler.GetExportedPdf.get
      x-methodName: getExportedPdf
      responses:
        200:
          description: Exported PDF.
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        # If section below is enabled, bug in connexion happens:
        # https://github.com/zalando/connexion/issues/1062
        # https://github.com/zalando/connexion/issues/840#issuecomment-464119001
        #400:
        #  description: Failed to export given URL.
        #  content:
        #    application/vnd.api+json:
        #      schema:
        #        $ref: '#/components/schemas/Errors'
      parameters:
        - name: path
          description: Relative UI URL under cloud.redhat.com domain.
          in: query
          schema:
            type: string
          example: rhel/vulnerability/cves?page=1
          required: true


components:
  schemas:
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              detail:
                type: string
                description: Error detail.
                example: Record not found.
              status:
                type: string
                description: String representation of HTTP status code.
                example: 404
            required:
              - detail
              - status
          minItems: 1
      required:
        - errors
    VersionOut:
      type: object
      properties:
        application_version:
          type: string
          description: Version of application.
          example: 0.1.2
      required:
        - application_version
