default:
  JIRA:
    # JIRA credentials for skipping tests failing due to existing bug
    username: jira_username
    password: jira_password
  VULNERABILITY:
    rest:
      # internal service hostname
      vuln_hostname: localhost
  USERS:
    primary_user:
      identity:
        account_number: "6089719"
        type: "User"
        user:
          username: "jdoe"
          email: "jdoe@acme.com"
          first_name: "John"
          last_name: "Doe"
          is_active: true
          is_org_admin: false
          is_internal: false
          locale: "en_US"
        internal:
          org_id: "3340851"
          auth_type: "basic-auth"
          auth_time: 6300
      entitlements:
        hybrid_cloud:
          is_entitled: true
        insights:
          is_entitled: true
        openshift:
          is_entitled: true
        smart_management:
          is_entitled: true
    no_entitlement:
      username: username
      password: password
    invalid:
      username: invalid
      password: invalid
dev:
  main:
    default_user: primary_user
    hostname: localhost:8300
    path: /
    api_path: api
    scheme: http
    ssl_verify: false
  http:
    default_auth_type: identity
    cacert_path: False
