openapi: "3.0.0"

info:
  title: Deep object filtering
  version: '1.0'

paths:
  /data:
    get:
      summary: Get data.
      description: Return data (with applied filters)
      operationId: connexion_deep_object_filters.getData
      responses:
        200:
          description: Data
          content:
            application/vnd.api+json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    details:
                      type: object
                      properties:
                        sap:
                          type: boolean
                          example: true
                        text:
                          type: string
                          example: xxee
                      required:
                        - sap
                        - text
                  required:
                    - details
                    - id
      parameters:
        - in: query
          name: filter
          description: Filter by deep object
          schema:
            type: object
            properties:
              id:
                type: integer
                example: 1
              details:
                type: object
                properties:
                  sap:
                    type: boolean
                    example: true
                  text:
                    type: string
                    example: xxee
          style: deepObject
          explode: true
