name: CI

on:
  push:
    branches:
      - "master"
      - "stable"
  pull_request:
    branches:
      - "master"
      - "stable"

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

