name: Pre-Commit Check

on:
  push:
    branches:
      - "master"
      - "stable"
  pull_request:
    branches:
      - "master"
      - "stable"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pre-Commit
        uses: pre-commit/action@v3.0.0
